history/urls.py
from django.urls import path

from . import views

app_name = "history"
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:artist_id>/', views.detail, name='detail'),
]

music/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('history/', include('history.urls')),
    path('admin/', admin.site.urls),
    ]

history/models.py
from django.db import models

class Artist(models.Model):
  artist_name = models.CharField(max_length=200)
  def __str__(self):
        return self.artist_name


class Song(models.Model):
  song_name = models.CharField(max_length=200)
  pub_year = models.IntegerField(default=0)
  duration = models.IntegerField(default=0)
  # artist = models.ForeignKey(Artist, on_delete=models.CASCADE)
  def __str__(self):
        return self.song_name

class SongArtist(models.Model):
  artist = models.ForeignKey(Artist, on_delete=models.CASCADE)
  song = models.ForeignKey(Song, on_delete=models.CASCADE)

history/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.template import loader

from .models import Artist, Song, SongArtist

# request contains the information we need from the forms

def index(request):
  artist_list = Artist.objects.all()
  context = {'artist_list': artist_list}
  return render(request, 'history/index.html', context)


def detail(request, artist_id):
    artist = Artist.objects.get(pk=artist_id)
    # student_list = Student.objects.filter(cohort_id=cohort_id)
    song_list = SongArtist.objects.filter(artist_id=artist_id)
    context = {'song_list': song_list, 'artist': artist}
    return render(request, 'history/detail.html', context)

history/templates/history/detail.html
  <h1>{{ artist.artist_name }}</h1>
  <ul>
    {% for song in song_list %}
        <li>{{ song.song.song_name }}</li>
    {% endfor %}
  </ul>

history/templates/history/index.html
{% if artist_list %}
    <ul>
    {% for artist in artist_list %}
        <li><a href="{% url 'history:detail' artist.id %}">{{ artist.artist_name }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No artists are available.</p>
{% endif %}